environment:

  matrix:
    - PYTHON: "C:\\Python27"
      SCONS_VERSION: "2.5.1"

install:
  - cd C:\\projects\\mgear_dist
  - git submodule update --init
  - git submodule foreach --recursive git checkout master
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install "scons==%SCONS_VERSION%"

before_test:

  - python --version
  - scons --version

build: off

# test_script:
#   - scons test
#   - scons unit-test

# branches:
#   only:
#     - master
# # enable service required for build/tests
# services:
#   - docker

# # scripts to run before build
# before_build:

# # to run your custom scripts instead of automatic MSBuild
# build_script:
#   - cmd: scons with-maya=2018